IDGS904_temaa1/Controllers/TienditaController.cs
using IDGS904_temaa1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IDGS904_temaa1.Controllers
{
    public class TienditaController : Controller
    {
        // GET: Tiendita
        public ActionResult Index()
        {
            var alumno = new Alumnos()
            {
                Nombre = "Pedro",
                Edad=20,
                Activo=false,
                Inscrito=new DateTime(2023,1,1)
            };
            ViewBag.Alumnos = alumno;
            return View();
        }

        public ActionResult Registrar() {

            return View();
        }

        public ActionResult Calculo()
        {
            double resultado = 0;
            if (TempData.ContainsKey("Resultado"))
            {
                resultado = (double)TempData["Resultado"];
            }
            ViewBag.valor=resultado;

            return View();
        }

        public RedirectToRouteResult Result(FtoC f)
        {
            TempData["Resultado"] = f.CaF();
            return RedirectToAction("Calculo");
        }
    }
}

IDGS904_temaa1/Views/Tiendita/Calculo.cshtml
@model IDGS904_temaa1.Models.FtoC

@{
    ViewBag.Title="Calculo";

}


<h2>Calculo</h2>


@using (Html.BeginForm("Result", "Tiendita", FormMethod.Post))
{



    <div class="form-group">

        @Html.LabelFor(model => Model.Grados, htmlAttributes:
        new { @class = "control-label col-md-2" })
    </div>
    <div class="col-md-10">

        @Html.EditorFor(model => model.Grados,
        new { htmlAttributtes = new { @class = "from-control" } })
    </div>

    <h5>Convertir a: </h5>

   
    @Html.RadioButtonFor(model => Model.tipo, "f") @Html.Label("F")
    <br>
    @Html.RadioButtonFor(model => Model.tipo, "c") @Html.Label("C")
    <br>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" name="name" value="Calcular" />
        </div>


    </div>
    <h2>@ViewBag.valor °</h2>
}

IDGS904_temaa1/Views/Tiendita/Index.cshtml
@{
    ViewBag.Title="Index";

}
<h1>Index</h1>


<h1>@Html.Display("Alumnos")</h1>

<hr/>
@Html.Editor("Alumnos")

IDGS904_temaa1/Views/Tiendita/Registrar.cshtml
@model IDGS904_temaa1.Models.Alumnos

@{
    ViewBag.Title="Registrar";

}


<h2>Registrar</h2>

@using (Html.BeginForm())
{

    <div class="form-group">

        @Html.LabelFor(model => Model.Nombre, htmlAttributes:
        new { @class = "control-label col-md-2" })
    </div>
    <div class="col-md-10">

        @Html.EditorFor(model => model.Nombre,
        new { htmlAttributtes = new { @class = "from-control" } })
    </div>


    <div class="form-group">

        @Html.LabelFor(model => Model.Edad, htmlAttributes:
        new { @class = "control-label col-md-2" })
    </div>
    <div class="col-md-10">

        @Html.EditorFor(model => model.Edad,
        new { htmlAttributtes = new { @class = "from-control" } })
    </div>


    <div class="form-group">

        @Html.LabelFor(model => Model.Activo, htmlAttributes:
        new { @class = "control-label col-md-2" })
    </div>
    <div class="col-md-10">

        @Html.EditorFor(model => model.Activo,
        new { htmlAttributtes = new { @class = "from-control" } })
    </div>


    <div class="form-group">

        @Html.LabelFor(model => Model.Inscrito, htmlAttributes:
        new { @class = "control-label col-md-2" })
    </div>
    <div class="col-md-10">

        @Html.EditorFor(model => model.Inscrito,
        new { htmlAttributtes = new { @class = "from-control" } })
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" name="name" value="Registrar" />
        </div>

    </div>
}

IDGS904_temaa1/Views/Tiendita/Result.cshtml
@{
    ViewBag.Title="Result";

}
<h1>Result</h1>